<?php
/**
 * Tumblr publishing handler with OAuth 2.0 auth and AI tool integration.
 *
 * Creates posts on a Tumblr blog via the Neue Post Format (NPF) API v2 with:
 * - Text content blocks (title heading + body) generated by the AI tool call
 * - Comma-separated tags (handler defaults + per-post override)
 * - Source URL attribution via the NPF `source_url` parameter
 * - Target blog resolution (configurable default or AI override)
 *
 * @package DataMachineSocials\Handlers\Tumblr
 * @since 0.17.0
 */

namespace DataMachineSocials\Handlers\Tumblr;

use DataMachine\Abilities\AuthAbilities;
use DataMachine\Core\EngineData;
use DataMachine\Core\Steps\Publish\Handlers\PublishHandler;
use DataMachine\Core\Steps\HandlerRegistrationTrait;
defined( 'ABSPATH' ) || exit;

/**
 * Tumblr Publishing Handler
 *
 * Publishes content to a Tumblr blog as NPF posts via API v2.
 */
class Tumblr extends PublishHandler {

	use HandlerRegistrationTrait;

	/** @var TumblrAuth|null Authentication handler */
	private $auth;

	/**
	* Constructor.
	*/
	public function __construct() {
		parent::__construct( 'tumblr' );

		self::registerHandler(
			'tumblr_publish',
			'publish',
			self::class,
			'Tumblr',
			'Publish a Tumblr post (Neue Post Format) with text content, tags, and source attribution',
			true,
			TumblrAuth::class,
			TumblrSettings::class,
			function ( $handler_slug, $handler_config, $engine_data ) {
				$blog_description = 'Tumblr blog identifier (blog name or hostname). Uses the configured default blog if omitted.';

				return array(
					'tumblr_publish' => array(
						'class'                   => self::class,
						'client_context_bindings' => array( 'job_id' ),
						'method'      => 'handle_tool_call',
						'handler'     => $handler_slug,
						'description' => 'Publish a Tumblr post with a title, body text, tags, and a source link back to the origin URL.',
						'parameters'  => array(
							'type'       => 'object',
							'properties' => array(
								'title'  => array(
									'type'        => 'string',
									'description' => 'Optional post title. Rendered as a heading at the top of the post.',
								),
								'body'   => array(
									'type'        => 'string',
									'description' => 'The main text body of the Tumblr post. Plain text; Tumblr renders it as an NPF text block.',
								),
								'tags'   => array(
									'type'        => 'string',
									'description' => 'Optional comma-separated tags for the post (e.g. "live music, charleston"). Merged with default tags from handler settings.',
								),
								'state'  => array(
									'type'        => 'string',
									'enum'        => array( 'published', 'queue', 'draft' ),
									'description' => 'Post state. Defaults to published.',
								),
								'blog_identifier' => array(
									'type'        => 'string',
									'description' => $blog_description,
								),
							),
							'required'   => array( 'body' ),
						),
					),
				);
			},
			'tumblr',
			array(
				'charLimit'        => 0,
				'maxImages'        => 0,
				'supportsCarousel' => false,
				'composer'        => array(
					'crossPostCompatible' => false,
					'mediaKinds'           => array( 'text' ),
					'ability'              => 'datamachine/tumblr-publish',
				),
				'capabilities'     => array(
					array( 'slug' => 'publish', 'label' => 'Publish' ),
				),
				'preview'          => array(
					'captionPosition' => 'below',
					'previewSurface'  => 'wide',
				),
			)
		);
	}

	/**
	* Lazy-load auth provider.
	*
	* @return TumblrAuth|null Auth provider instance or null if unavailable.
	*/
	private function get_auth() {
		if ( null === $this->auth ) {
			$auth_abilities = new AuthAbilities();
			$this->auth     = $auth_abilities->getProvider( 'tumblr' );

			if ( null === $this->auth ) {
				$this->log(
					'error',
					'Tumblr Handler: Authentication service not available',
					array(
						'handler'             => 'tumblr',
						'available_providers' => array_keys( $auth_abilities->getAllProviders() ),
					)
				);
			}
		}
		return $this->auth;
	}

	/**
	* Execute Tumblr publishing.
	*
	* @param array $parameters Tool parameters including title, body, tags, state, blog_identifier.
	* @param array $handler_config Handler configuration from settings.
	* @return array {
	* @type bool $success Whether the post was created.
	* @type string $error Error message if failed.
	* @type string $tool_name Tool identifier.
	* @type array $data Post data on success (post_id, post_url).
	* }
	*/
	protected function executePublish( array $parameters, array $handler_config ): array {
		$body = trim( (string) ( $parameters['body'] ?? '' ) );
		if ( '' === $body ) {
			return $this->errorResponse( 'Tumblr post body is required', array() );
		}

		$engine = $parameters['engine'] ?? null;
		if ( ! $engine instanceof EngineData ) {
			$engine = new EngineData( $parameters['engine_data'] ?? array(), $parameters['job_id'] ?? null );
		}

		$source_url = $engine->getSourceUrl();

		$blog_identifier = $this->resolve_blog_identifier( $parameters, $handler_config );
		if ( '' === $blog_identifier ) {
			return $this->errorResponse(
				'No blog_identifier provided. Set a default in handler settings or pass the blog_identifier parameter.',
				array()
			);
		}

		$auth = $this->get_auth();
		if ( ! $auth ) {
			return $this->errorResponse( 'Tumblr authentication not configured', array(), 'critical' );
		}

		$token = $auth->get_valid_access_token();
		if ( empty( $token ) ) {
			return $this->errorResponse( 'Tumblr access token is missing or expired — re-authorize in WP Admin > Data Machine > Settings', array(), 'critical' );
		}

		$content_blocks = array();
		$title          = trim( (string) ( $parameters['title'] ?? '' ) );
		if ( '' !== $title ) {
			$content_blocks[] = array(
				'type'    => 'text',
				'subtype' => 'heading1',
				'text'    => mb_substr( $title, 0, 1000 ),
			);
		}
		$content_blocks[] = array(
			'type' => 'text',
			'text' => $body,
		);

		$tags = $this->resolve_tags( $parameters, $handler_config, $engine, $source_url );

		$payload = array(
			'content' => $content_blocks,
			'tags'    => $tags,
			'state'   => in_array( $parameters['state'] ?? '', array( 'published', 'queue', 'draft' ), true )
				? $parameters['state']
				: 'published',
		);

		if ( ! empty( $source_url ) ) {
			$payload['source_url'] = $source_url;
		}

		$this->log(
			'info',
			'Tumblr: Creating post',
			array(
				'blog'    => $blog_identifier,
				'state'   => $payload['state'],
				'tag_count' => '' === $tags ? 0 : count( explode( ',', $tags ) ),
				'source_url' => $source_url,
			)
		);

		try {
			$result = $this->httpPost(
				'https://api.tumblr.com/v2/blog/' . rawurlencode( $blog_identifier ) . '/posts',
				array(
					'headers' => array(
						'Authorization' => 'Bearer ' . $token,
						'Content-Type'  => 'application/json',
					),
					'body'    => wp_json_encode( $payload ),
					'context' => 'Tumblr Post Creation',
				)
			);

			if ( ! $result['success'] ) {
				return $this->errorResponse(
					'Tumblr API request failed: ' . ( $result['error'] ?? 'Unknown error' ),
					array( 'result' => $result )
				);
			}

			$status_code   = $result['status_code'] ?? 0;
			$decoded       = json_decode( $result['data'] ?? '', true );
			$response_data = is_array( $decoded ) ? ( $decoded['response'] ?? array() ) : array();

			if ( in_array( $status_code, array( 200, 201 ), true ) && ! empty( $response_data['id'] ) ) {
				$post_id = (string) $response_data['id'];
				$post_url = 'https://' . self::hostname_for( $blog_identifier ) . '/post/' . $post_id;

				$this->log(
					'info',
					'Tumblr: Post created successfully',
					array(
						'post_id' => $post_id,
						'blog'    => $blog_identifier,
					)
				);

				return $this->successResponse(
					array(
						'post_id'  => $post_id,
						'post_url' => $post_url,
					)
				);
			}

			$api_msg = is_array( $decoded ) ? ( $decoded['meta']['msg'] ?? '' ) : '';
			$error_msg = 'Tumblr API error';
			if ( ! empty( $api_msg ) ) {
				$error_msg .= ': ' . $api_msg;
			}

			return $this->errorResponse(
				$error_msg,
				array(
					'http_code'    => $status_code,
					'api_response' => $result['data'] ?? '',
				)
			);
		} catch ( \Exception $e ) {
			return $this->errorResponse(
				$e->getMessage(),
				array( 'exception_type' => get_class( $e ) )
			);
		}
	}

	/**
	 * Resolve the target blog identifier.
	 *
	 * Resolution order: AI parameter → handler config default.
	 *
	 * @param array $parameters Tool parameters.
	 * @param array $handler_config Handler configuration.
	 * @return string Blog identifier (empty if none resolved).
	 */
	public function resolve_blog_identifier( array $parameters, array $handler_config ): string {
		if ( ! empty( $parameters['blog_identifier'] ) ) {
			return trim( (string) $parameters['blog_identifier'] );
		}

		$default = trim( (string) ( $handler_config['blog_identifier'] ?? '' ) );
		return $default;
	}

	/**
	 * Resolve the comma-separated tags string.
	 *
	 * Merges handler-configured default tags with the per-post tags parameter.
	 *
	 * @param array             $parameters Tool parameters.
	 * @param array             $handler_config Handler configuration.
	 * @param EngineData|null   $engine Engine data instance.
	 * @param string            $source_url Source URL for post-id context.
	 * @return string Comma-separated tags.
	 */
	public function resolve_tags( array $parameters, array $handler_config, $engine, string $source_url ): string {
		$engine;
		$source_url;
		$merged = array();

		$default_tags = (string) ( $handler_config['default_tags'] ?? '' );
		foreach ( explode( ',', $default_tags ) as $tag ) {
			$tag = trim( $tag );
			if ( '' !== $tag ) {
				$merged[] = $tag;
			}
		}

		$param_tags = (string) ( $parameters['tags'] ?? '' );
		foreach ( explode( ',', $param_tags ) as $tag ) {
			$tag = trim( $tag );
			if ( '' !== $tag && ! in_array( $tag, $merged, true ) ) {
				$merged[] = $tag;
			}
		}

		return implode( ', ', $merged );
	}

	/**
	 * Normalize a blog identifier to a hostname for URL construction.
	 *
	 * A bare blog name (e.g. "extrachill") becomes "extrachill.tumblr.com";
	 * a hostname or custom domain is returned as-is.
	 *
	 * @param string $blog_identifier Blog name or hostname.
	 * @return string Hostname suitable for a post URL.
	 */
	public static function hostname_for( string $blog_identifier ): string {
		$blog_identifier = trim( $blog_identifier );
		if ( '' === $blog_identifier ) {
			return 'tumblr.com';
		}

		if ( false !== strpos( $blog_identifier, '.' ) ) {
			return $blog_identifier;
		}

		return $blog_identifier . '.tumblr.com';
	}

	/**
	* Get handler display label.
	*
	* @return string Translated label.
	*/
	public static function get_label(): string {
		return __( 'Post to Tumblr', 'data-machine-socials' );
	}
}
